name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag prefix'
        default: 'preview'
        required: true

permissions:
  contents: read

jobs:
  release:
    uses: fluxcd/gha-workflows/.github/workflows/release.yml@release
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
